### ISSUE TITLE
Create new category failed

### ISSUE THREAD

**Issue by klamma** [rwth-acis/RequirementsBazaar-WebFrontend#129]
According to some students from the mixed reality lab and also based on my experience, creating a new category in project https://requirements-bazaar.org/projects/468 failed. I used a firefox

**Comment by fxjordan** [comment]
Error seems to be authorization related. `POST https://requirements-bazaar.org/bazaar/categories` fails with:

```
{
    "message": "Only admins can create categories.",
    "errorCode": "AUTHORIZATION",
    "exceptionCode": 4003,
    "exceptionMessage": "Only admins can create categories. Error in Bazaar service: This user is not authorized to use this method. ExceptionCode: 4003.",
    "suppressed": [],
    "localizedMessage": "Only admins can create categories."
}
```

**Comment by fxjordan** [comment]
The backend service checks whether a user has the `PrivilegeEnum.Create_CATEGORY` privilege for the specific project. This privilege is only available to users with the role `ProjectAdmin`. Should we change this behavior @klamma ?

**Comment by istvank** [comment]
The best way would be to complete the branch dealing with the authorization management. The goal was to add a GitLab-like UI to assign project managers and members, who can create new categories. There is also a documentation in the backend repository about which user can do what. If I remember correctly, that's not only the admin.

**Comment by klamma** [comment]
Who has the role projectadmin for every project in the moment?

**Comment by klamma** [comment]
It would be perhaps a good idea if the frontend is displaying the error message to the user.

**Comment by fxjordan** [comment]
> Who has the role projectadmin for every project in the moment?

The 'ProjectAdmin' role is assigned to the user who creates a project. @istvank is right, not only the admin but also users with the role 'ProjectManager' can create new categories. However, assigning all students the manager role might be a problem because managers can also modify comments, requirements and attachments (see https://github.com/rwth-acis/RequirementsBazaar/blob/master/docs/Privileges.md).

**Comment by fxjordan** [comment]
Users can not be added to a project with the role _ProjectManager_ or _ProjectAdmin_ to allow them creating new categories. Other users will get an error message explaining the reason.
