### ISSUE TITLE
Only project creators can add new categories

### ISSUE THREAD

**Issue by BenediktHensen** [rwth-acis/RequirementsBazaar-WebFrontend#146]
If you create a project, nobody apart from the project creator is able to add new categories. If other users click the "Add New Category" button, they can still enter the title and description but as soon as "Save" is clicked, the editing form disappears again and no new category is created.

**Comment by fxjordan** [comment]
You can now manage project member roles as the creator of a project. Feel free to check the new feature on the Live instance: https://requirements-bazaar.org
