### ISSUE TITLE
Unable to delete requirement

### ISSUE THREAD

**Issue by BenediktHensen** [rwth-acis/RequirementsBazaar-WebFrontend#147]
After creating a new requirement, I cannot delete it anymore. If I select "Delete Requirement" from the context menu, a confirmation window appears but after clicking the red "Yes" button, the confirmation window closes and the requirement still exists.

**Comment by fxjordan** [comment]
Seems like currently, users need the _Modify_REQUIREMENT_ privilege to delete a requirement. This privilege is only granted to users with role _ProjectManager_ or higher. But shouldn't be the creator of a requirement always be allowed to delete it again? @klamma At least for some time X after creating it, I think.

**Comment by AlexanderNeumann** [comment]
#236 same issue right? At least the author should be able to delete the requirement. If it was created by mistake for example.

**Comment by fxjordan** [comment]
The problem should be fixed, and I'll deploy it together with some frontend fixes this evening. (@aparkova )

**Comment by fxjordan** [comment]
Changes are deployed. Also added a loading indicator while the request is in progress.
