### ISSUE TITLE
Activity tracker not updated on live instance

### ISSUE THREAD

**Issue by fxjordan** [rwth-acis/RequirementsBazaar-WebFrontend#159]
The activity tracker works fine on the beta instance, but for some reason the feed on the live instance is not updated when a new requirement is created

**Comment by fxjordan** [comment]
After remote debugging through an SSH tunnel (puh *_* ...) I found out an SQL exceptions is thrown during the storeActivity() method. However, this exceptions is caught again and logged on the FINEST log level which does not end up in the log file...
I already opened an issue because unexpected exceptions must be logged at least at WARNIGN or ERROR level (see: https://github.com/rwth-acis/las2peer-ActivityTracker/issues/51)

The SQL exception that seems to occur when an activity is created is:
```
org.jooq.exception.DataAccessException: SQL [insert into "activity" ("creation_date", "activity_action", "origin", "data_url", "data_type", "data_frontend_url", "parent_data_url", "parent_data_type", "user_url", "additional_object", "public", "stale") values (cast(? as timestamp(6) with time zone), ?, ?, ?, ?, ?, ?, ?, ?, cast(? as json), ?, ?) returning "activity"."id", "activity"."creation_date", "activity"."activity_action", "activity"."origin", "activity"."data_url", "activity"."data_type", "activity"."data_frontend_url", "activity"."parent_data_url", "activity"."parent_data_type", "activity"."user_url", "activity"."additional_object", "activity"."public", "activity"."stale"];

ERROR: duplicate key value violates unique constraint "activity_pkey"
  Detail: Key (id)=(207) already exists.
```

**Comment by fxjordan** [comment]
It turned out the auto increment sequence on the production database was out of sync with the IDs in the activity table. This might have happened when older activities were imported into the database.

`SELECT nextval(pg_get_serial_sequence('activity', 'id'))` returned **209** while investigating the issue, but the maximum ID value in the table was actually **12626**.

The error could be fixed by manually updating the sequence to the MAX ID value +1 using the following command:
```
SELECT SETVAL((SELECT pg_get_serial_sequence('activity', 'id')), (SELECT MAX(id) + 1 FROM activity), FALSE);
```

I should add here that JOOQ used the _identity column type_ (https://www.postgresqltutorial.com/postgresql-identity-column/) to implement the auto-increment property, which is defined in the code. Therefore, once cannot find a named sequence when investigating the issue (e.g., in pgAdmin). Postgres defines the `pg_get_serial_sequence('table_name', 'column_name')` query to work with sequences used for identity columns.

The activity tracker is now working again, without any code changes. However, https://github.com/rwth-acis/las2peer-ActivityTracker/issues/51 is still a problem in my opinion.

**Comment by klamma** [comment]
Great. What happened to the date and the clickable links in the activity tracker frontend?

**Comment by fxjordan** [comment]
It seems that the new frontend did not have a date yet. I'dd add that. The clickable items are implemented in  (https://github.com/rwth-acis/RequirementsBazaar-WebFrontend/pull/172) but not yet released.

**Comment by istvank** [comment]
That would be relative times à la "five minutes ago", right? Just like in requirements cards.

**Comment by fxjordan** [comment]
Yes, I actually described that in #178 :)
