### ISSUE TITLE
Completed requirements not marked as done

### ISSUE THREAD

**Issue by istvank** [rwth-acis/RequirementsBazaar-WebFrontend#164]
After clicking "mark as done" on a requirement, nothing happens, except that the last activity timer gets updated. Example:
https://requirements-bazaar.org/projects/2/requirements/2762
Related to this, when clicking "Completed Requirements" in the category view, it does not show up, instead it just says "Nothing to see here". I think that was due to the quick release last year.

**Comment by fxjordan** [comment]
In a first step, every realized requirement gets a 'Done' label immediately when the user changes the status, so users are aware of the changed state.
Next, when the list is reloaded or the tabs are changed the requirement should only be displayed in the correct tab (incomplete, completed)
![image](https://user-images.githubusercontent.com/6236455/150689952-ef457195-c44f-4767-beed-477f71199597.png)

**Comment by fxjordan** [comment]
Resolved by #169
