### ISSUE TITLE
Remove development timeline view from project page

### ISSUE THREAD

**Issue by fxjordan** [rwth-acis/RequirementsBazaar-WebFrontend#175]
The timeline component seems to be very useful for tracking development progress on a single requirement. However, on the project level, the current semantic of the timeline do not seem to be useful at all.
- The state 'Development Started' only indicates a Git repository was linked.
- The state 'Development in Progress' indicates that at least one Pull Request was created.
- The state 'Released' indicates that at least one GitHub release was published.

The same information can be observed by users by just using the "Show on GitHub" button and look at the more development related information there.

Instead of the timeline, we could:
- add a progress bar showing how much of the existing requirements are already realized #176 
- allow project owners to mark a project as 'done' or 'finished' as it's labeled as such in the project list, or users can filter the list and view only 'active' projects #177

**Comment by istvank** [comment]
Maybe the timeline should only be shown for requirements in categories that have been linked to GitHub. Otherwise, they just add to the visual complexity of a component view.

**Comment by fxjordan** [comment]
I was thinking the same thing, but came up with the idea that users could change the state manually (#166).
But now that I think about it, removing it is the better option (or at least allow project owners to disable it) because there is more effort than benefit when changing the development progress manually.

**Comment by istvank** [comment]
On the other hand, it nudges people to really link issues to requirements. But still, the disadvantages of the UI cluttered with (empty) timelines are overwhelming.

**Comment by fxjordan** [comment]
Also, there are other ways to encourage people using the feature more:

For requirements without a linked issue, we add a "Create GitHub issue" button at the same place where the "See on GitHub" button is, if there is already a linked issue.
![Bildschirmfoto 2022-01-26 um 14 53 14](https://user-images.githubusercontent.com/6236455/151175981-67a23b73-ca02-49e0-8d37-c4e59e5a7218.png)

**Comment by istvank** [comment]
Do you have an example link to a requirement with "See on GitHub" button? I am wondering that it is so prominently placed on the top right. Should be rather somewhere close to the Development Timeline.

**Comment by fxjordan** [comment]
https://beta.requirements-bazaar.org/projects/110/categories/317 (the layout to the top right is not yet deployed on beta. It looked even worse before).

**Comment by istvank** [comment]
Oh, that does not look great. 😅  Maybe instead of the button can be more something like an underlined, subtle link below "Development Timeline".

**Comment by fxjordan** [comment]
Sounds like a good idea.
When using the website from a mobile device, it becomes even more clear that there are too many large buttons on the component.

I think some of this information and the actions can be better visualized on the detail page for a single requirement. With #170 I started including this detail page more in the overall concept of the website anyway.

**Comment by istvank** [comment]
Yes. An initial GitHub button could also be hidden in the ... menu.
