### ISSUE TITLE
Add basic statistics to landing page

### ISSUE THREAD

**Issue by fxjordan** [rwth-acis/RequirementsBazaar-WebFrontend#182]
Makes the landing page more attractive and visitors realize it's actually used

**Comment by fxjordan** [comment]
Preview of WIP:
![image](https://user-images.githubusercontent.com/6236455/151590924-907e915e-b899-4712-8ef8-f11a8de56be2.png)

**Comment by istvank** [comment]
Looks great! These numbers were animated using a short count-up animation. Also, we had a list of three recently active projects.

**Comment by fxjordan** [comment]
I've already added such an animation. And a list of featured projects is also in my mind. I got some inspirations from an old screenshots on Twitter https://twitter.com/reqbaz/status/912959989794426880?s=20&t=ztFvC7Xz1ntC1ENsgQKH6A

**Comment by istvank** [comment]
Hey, btw a Twitter bot is a good idea, we should ask @AlexanderNeumann :)

**Comment by fxjordan** [comment]
Yes, we already talked about examples like announcing new projects or a project of the month again on Twitter a while ago.

In terms of actual bots, there could be a bot which transfers a discussion from Twitter into a new requirement in some project (just a quick idea)

**Comment by fxjordan** [comment]
Another point in context of this issue: I think the number of users would be a nice metric on the landing page too. But maybe only  "active users in the last X (month, year)" ?

**Comment by istvank** [comment]
Yes, depending on the actual figures. ;)
