### ISSUE TITLE
Describe features better on landing page

### ISSUE THREAD

**Issue by fxjordan** [rwth-acis/RequirementsBazaar-WebFrontend#183]
Here's a first draft for a new 'features' section as it is included in most landing pages of App, Webapps, etc. today:

![image](https://user-images.githubusercontent.com/6236455/151600555-3e741ddc-c525-450e-bad8-0bf5163b98d5.png)

I think the texts can be still improved, but this should be good start for some ideas @istvank @klamma 

I've written the texts from the perspective of 'Project Owners' because they need to be convinced of using the application in the first place.

**Comment by istvank** [comment]
Great! Maybe "Vote for Requirements" instead of Voting. Then it applies to project owners as well as users. Are the icons PD?

**Comment by fxjordan** [comment]
"Vote" definitely sounds better and fits better to the other two. But I changed it because of my "perspective" thoughts...
What is PD?

**Comment by istvank** [comment]
public domain, but I see you added the licenses in "About".
