### ISSUE TITLE
Project information not updated immediately

### ISSUE THREAD

**Issue by klamma** [rwth-acis/RequirementsBazaar-WebFrontend#239]
After having added a new requirement the project information was still the old. Sorting projects according to last activity had no effect, in consequence.

**Comment by klamma** [comment]
<img width="826" alt="Bildschirmfoto 2022-04-27 um 10 10 32" src="https://user-images.githubusercontent.com/6756/165473073-53d120ea-2888-4295-8585-5f40
<img width="420" alt="Bildschirmfoto 2022-04-27 um 10 10 20" src="https://user-images.githubusercontent.com/6756/165473096-d2667b26-4f7f-4a3f-aae1-b24ded77fd7c.png">
48202b1c.png">

**Comment by klamma** [comment]
<img width="826" alt="Bildschirmfoto 2022-04-27 um 10 10 32" src="https://user-images.githubusercontent.com/6756/165473158-9732223f-d81c-49db-a698-679f17fe4417.png">

**Comment by klamma** [comment]
<img width="420" alt="Bildschirmfoto 2022-04-27 um 10 10 20" src="https://user-images.githubusercontent.com/6756/165473368-b4770c64-16b3-464a-b474-3ca0b21f345e.png">

**Comment by fxjordan** [comment]
I just tried to reproduce this, but the numbers updated correctly (using the back button as well as clicking the project in the breadcrumb navigation). Can you still reproduce this?
