### ISSUE TITLE
Mobile UI is cluttered

### ISSUE THREAD

**Issue by klamma** [rwth-acis/RequirementsBazaar-WebFrontend#252]
I have noticed that some buttons and elements are not reachable on the mobile phone anymore. 
![grafik](https://user-images.githubusercontent.com/6756/168104478-6fb1ba11-b6aa-48e1-839f-d9f000eaef35.png)

**Comment by fxjordan** [comment]
I fixed a lot of small issues with #260 and added a new navigation bar, so ReqBaz should now be a lot more usable on mobile.
Changes are already available on [requirements-bazaar.org](https://requirements-bazaar.org)
